# Create development environment for cocci-custom OctoberCMS project.
# The Docker image is based on https://hub.docker.com/_/ubuntu/
version: '3'
services:
  # Nginx & PHP
  october-web-server:
    env_file: .env
    image: spycetek/aep:a2.0-1.18-7.4-2
    privileged: true
    command: /sbin/init
    #entrypoint: /root/start_nginx_php-fpm.sh
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${HTTP_PORT}:80"
      - "80:80"
    networks:
      - local-net
    volumes:
      # Don't mount to /var/www because it's web server user's home directory
      # and we don't want to mess it up.
      - ${DOCKER_VOLUME_DIR}:/var/www/html:cached
    environment:
      # This is used to know if the container is created by this docker-compose
      # from inside of the container.
      - IS_OCT_CONTAINER=1

  # Enable HTTPS with localhost
  https-portal:
    image: steveltn/https-portal:1
    container_name: https-portal
    ports:
      - '443:443'
      - "50081:80" # Not used, but for preventing host:80 mapped to https-portal:80
    links:
      - october-web-server
    environment:
      STAGE: local
      DOMAINS: ${HTTPS_DOMAINS}
      CLIENT_MAX_BODY_SIZE: 50M
    networks:
      - local-net

# Network is required to enable container access another container.
networks:
  local-net:
    external: true
