# Create development environment for cocci-custom OctoberCMS project.
# The Docker image is based on https://hub.docker.com/_/ubuntu/
version: '3'
services:
  october-web-server:
    env_file: .env
    image: spycetek/aep:a2018.03.0-1.14-7.2-3
    entrypoint: tail -f /dev/null
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${HTTP_PORT}:80
    networks:
      - local-net
    volumes:
      # Don't mount to /var/www because it's web server user's home directory
      # and we don't want to mess it up.
      - ${DOCKER_VOLUME_DIR}:/var/www/html:cached

# Network is required to enable container access another container.
networks:
  local-net:
    external: true
